apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  labels:
    group: mongo
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - name: mongodb
          image: mongo:3.6.21-xenial
          volumeMounts:
            - name: mongodb-persistent-storage
              mountPath: /data/db/
      volumes:
        - name: mongodb-persistent-storage
          persistentVolumeClaim:
            claimName: mongodb-pvc

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-express
  labels:
    group: mongo
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: mongo-express
  template:
    metadata:
      labels:
        app: mongo-express
    spec:
      containers:
        - name: mongo-express
          image: mongo-express:latest
          env:
            - name: ME_CONFIG_MONGODB_SERVER
              value: fleetman-mongodb

---
apiVersion: v1
kind: Service
metadata:
  name: fleetman-mongodb
  labels:
    group: mongo
spec:
  selector:
    app: mongodb
  ports:
    - name: mongodb
      port: 27017

---
apiVersion: v1
kind: Service
metadata:
  name: fleetman-mongo-express
  labels:
    group: mongo
spec:
  type: NodePort
  selector:
    app: mongo-express
  ports:
    - name: mongo-express
      port: 8081
      nodePort: 30081
