apiVersion: v1
kind: Service
metadata:
  name: fleetman-queue
spec:
  type: NodePort
  selector:
    app: activemq
  ports:
    - name: activemq
      port: 61616
      #nodePort: # `type` applies to all ports: a random one is generated
    - name: web-admin
      port: 8161
      nodePort: 30010

---
apiVersion: v1
kind: Service
metadata:
  name: fleetman-position-tracker
spec:
  selector:
    app: position-tracker
  ports:
    - name: web
      port: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: fleetman-api-gateway
spec:
  selector:
    app: api-gateway
  ports:
    - name: web
      port: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: fleetman-web-app
spec:
  type: NodePort
  selector:
    app: web-app
  ports:
    - name: web
      port: 80
      nodePort: 30080
