- hosts: localhost
  gather_facts: false
  vars:
    replicas: 4

  tasks:
    - name: Scale the Hello Go deployement by strategic merge
      k8s:
        state: present
        merge_type: strategic-merge
        resource_definition:
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: hello-go
            namespace: default
          spec:
            replicas: "{{ replicas }}"
