apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    tier: back-end
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
      tier: back-end
  template:
    metadata:
      name: nginx
      labels:
        app: nginx
        tier: back-end
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80
          volumeMounts:
            - name: code
              mountPath: /app/code/
            - name: config
              mountPath: /etc/nginx/conf.d/
      volumes:
        - name: code
          persistentVolumeClaim:
            claimName: code
        - name: config
          configMap:
            name: nginx-config
            items:
              - key: config
                path: site.conf
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    tier: back-end
spec:
  #  externalIPs:
  #    -
  type: LoadBalancer
  selector:
    app: nginx
    tier: back-end
  ports:
    - protocol: TCP
      port: 80
